
COLUMNS = [
    "Job",
    "Quote",
    "Rep",
    "Job Name",
    "Contact",
    "Ph/Mob",
    "email",
    "Deliver",
    "ACCNT",
    "CASH",
    "Due Date",
    "Due Time",
    "Date taken",
    "COMPLETED BY",
    "NOTIFIED BY",
    "COMPLETED BY Date",
    "NOTIFIED BY Date",
    "COMPLETED TIME",
    # "NOTIFIED TIME",
    "PRINT & ART TOTAL QUOTED",
    "TODAY",
    "WIP",
    "JOF",
    "USB/DISC",
    "HARDCOPY",
    "TO BE SENT",
    "PAGEFLEX",
    "RERUN",
    "CHANGES",
    "NO CHANGES",
    "FILE LOCATION",
    "PROOF APPROVED BY Date",
    "PROOF APPROVED BY  TIME",
    "PRINT READY",
    "PREPRESS REQUIRED",
    "METAL PLATES",
    "PRISMA",
    "NO PROOF",
    "YES PROOF",
    "PROOF APPROVED",
    "MASTERS FILE LOCATION:",
    "NOTIFICATION METHOD",
    "MASTERS JOB TYPE : Copy",
    "JOB QUOTE SHEET",
    "ACCOUNT TYPE",
    "ART MENU",
    "PROOF",
    "APPROVED METHOD",
    "approval recieved by",
    "Art Notes",
    "PAPER SIZE",
    "COLOUR / BW",
    "BLEED",
    "WIDE FORMAT",
    "PAPER WEIGHT",
    "PAPER COLOUR",
    "PAPER TYPE",
    "HOW MANY COPYS",
    "SIDES",
    "ORIGINAL PAGES",
    "COL PAGES",
    "B&W PAGES",
    "ARTIST",
    "ART TOTAL QUOTED",
    "ENVELOPES",
    "OFFICE STATIONARY",
    "MAGNETS",
    "LABELS",
    "BANNERS",
    "CD/DVD",
    "CARBON BOOKS",
    "CARBON BOOKS SIDES",
    "CARBON BOOKS NUMBERS",
    "CARBON BOOKS SETS",
    "CARBON BOOKS STOCK 1",
    "CARBON BOOKS STOCK 2",
    "CARBON BOOKS STOCK 3",
    "CARBON BOOKS STOCK 4",
    "CARBON BOOKS BIND",
    "CARBON BOOKS BIND EDGE",
    "CARBON BOOKS BIND COVER TYPE",
    "FINNISH",
    "BINDING",
    "CUT",
    "DRILL",
    "DRILL SIZE",
    "staple no",
    "staple where",
    "staple HOW",
    "padding",
    "padding sheets",
    "perf",
    "SCORE",
    "COLLATE QTY",
    "COLLATE HOW",
    "COLLATE",
    "PERF/SCORE",
    "PART",
    "PART OF",
    "perf1",
    "perf2",
    "buttons",
    "perf3",
    "perf4",
    "perf5",
    "perf6",
    "perf7",
    "perf8",
    "perf9",
    "perf10",
    "on",
    "off",
    "on/off",
    "on/off display",
    "jobsheet number",
    "HOW MANY bus cards",
    "bus card type",
    "bus card sides",
    "bus laminate",
    "bus metalic",
    "bus slimline",
    "bus round corners",
    "bus diecut",
    "CAL type",
    "CAL style",
    "CAL FRIDGE",
    "CAL size",
    "CAL scape",
    "BIND BOOK",
    "BIND MEDIA",
    "COVER STOCK OUT",
    "COVER GSM",
    "COVER bleed",
    "customer art",
    "COVER STOCK IN",
    "PRODUCTION NOTES",
    "COV IN COL",
    "COV OUT COL",
    "COVER GSM IN",
    "F COVER",
    "B COVER",
    "COIL SIZE",
    "HOW MANY COPYS CALENDARS",
    "staple HOW CAL",
    "PAPER TYPE CAL",
    "PAPER WEIGHT CAL",
    "SIDES CAL",
    "BLEED CAL",
    "COLOUR / BW CAL",
    "BIND BOOK CAL",
    "BIND MEDIA CAL",
    "COVER bleed CAL",
    "COVER STOCK OUT CAL",
    "COVER STOCK IN CAL",
    "COV OUT COL CAL",
    "COIL SIZE Cal",
    "F COVER CAL",
    "COV IN COL CAL",
    "COVER GSM CAL",
    "COVER GSM IN CAL",
    "FINNISH CAL",
    "CUT CAL",
    "DRILL CAL",
    "DRILL SIZE CAL",
    "staple no CAL",
    "staple where CAL",
    "padding CAL",
    "padding sheets CAL",
    "PRODUCTION NOTES CAL",
    "BLEED bus",
    "B COVER Cal",
    "COL PAGES Cal",
    "HOW MANY COPYS Stat",
    "colour inks Stat",
    "colour inks Stat 2",
    "colour inks Stat 3",
    "BIND BOOK STAT",
    "perf  1 stat",
    "perf  2 stat",
    "perf  3 stat",
    "perf  4 stat",
    "PAPER SIZE LABEL",
    "PAPER SIZE CARDS",
    "HOW MANY COPYS CARDS",
    "PAPER TYPE CAL LABEL",
    "PAPER TYPE CARDS",
    "PAPER WEIGHT LABEL",
    "PAPER WEIGHT CARDS",
    "SIDES CARDS",
    "BLEED CARDS",
    "COLOUR / BW CARDS",
    "PAPER COLOUR CARDS",
    "CARD TYPE",
    "CARD IN COL",
    "CARD OUT COL",
    "PRODUCTION NOTES BANNERS & dvd",
    "HOW MANY COPYS LABELS",
    "lABEL TYPE",
    "BLEED LABEL",
    "PAPER COLOUR LABEL",
    "CUT CARDS",
    "CUT LABEL",
    "FINNISH CARDS",
    "FINNISH LABEL",
    "DRILL SIZE CARDS",
    "DRILL CARDS",
    "perf CARDS",
    "sCORE CARDS",
    "perf1 CARDS",
    "COLOUR / BW LABELS",
    "lABEL SHEETS",
    "lABEL BOXES",
    "lABEL COMM ROLL",
    "lABEL COMM ROLL STOCK",
    "COLOUR / BW  COMM LABELS",
    "HOW MANY COPYS BAN",
    "HOW MANY COPYS DVD",
    "BAN TYPE",
    "dvd TYPE",
    "BAN LAM",
    "PAPER TYPE Copy2",
    "BAN SIZE",
    "BAN SNAP",
    "BAN HOW",
    "BAN HOW Copy",
    "BAN STYLE",
    "DVD BURN",
    "DVD DISC TYPE",
    "DVD DISC SLIM CASE",
    "PRODUCTION NOTES  CARDS & LABELS",
    "HOW MANY COPYS fABRIC",
    "DVD FABRIC TYPE Copy",
    "FABRIC product type",
    "PAPER TYPE FABRIC  PLACEMENT",
    "PRODUCTION NOTES STAT",
    "JOB QUOTE SHEET CARDS",
    "JOB QUOTE SHEET dvd",
    "Field 251",
    "JOB LOCATION",
    "LAM HOW MANY",
    "LAM TYPE",
    "LAM SIZE",
    "LAM HOW MANY 2",
    "LAM SIZE 2",
    "LAM TYPE 2",
    "WIDE MOUNTING",
    "Field 260",
    "SUB CONTRACTORS",
    "DUE BACK Date",
    "DATE SENT",
    "Field 264",
    "JOB COMPLETED",
    "PRODUCTION NOTES  BIZ CARDS",
    "CARBON BOOKS STOCK size",
    "COVER STOCK IN ASF",
    "ENVELOPES SIDES",
    "HOW MANY COPYS raff",
    "CARBON BOOKS STOCK raff  size",
    "CARBON BOOKS STOCK 1 raff",
    "CARBON BOOKS STOCK 2 raff",
    "CARBON BOOKS STOCK 3 raff",
    "perf2 raff",
    "perf  1 stat raff",
    "perf  2 stat raff",
    "perf  3 stat raff",
    "CARBON BOOKS SETS raff",
    "CARBON BOOKS NUMBERS raff",
    "CARBON BOOKS BIND EDGE raff",
    "CARBON BOOKS BIND COVER TYPE raff",
    "CARBON BOOKS BIND raff",
    "COV IN COL RAFF",
    "COV OUT COL RAFF",
    "COV OUT COL RAFF BODY",
    "COVER GSM RAFF F",
    "COVER GSM RAFFBODY",
    "COVER GSM RAFF BACK",
    "SIDES raff",
    "staff member",
    "STAFF WITH JOB",
    "STAFF WITH JOB Copy",
    "COMPLETED JOB LOCATION",
    "PRODUCTION NOTES design",
    "Art Type",
    "PREsentation pocket",
    "Job Type",
    "HOW MANY promo",
    "Promo TYPE",
    "PRODUCTION NOTES PROMO",
    "ORDER CODE",
    "MODEL CODE",
    "MODEL COL",
    "PROMO PRINT AREA 1",
    "Promo PRINT COL 1",
    "Promo PRINT COL 2",
    "Promo PRINT COL 3",
    "Promo PRINT COL 4",
    "PROMO PRINT AREA 2",
    "ORDER CODE Banner",
    "Charge method",
    "In Art Date",
    "PRODUCTION NOTES Rubber stamp",
    "Rubber Stamp TYPE",
    "Rubber stamp details",
    "Rubber stamp details Copy",
    "Rubber stamp details Copy2",
    "Rubber stamp details Copy3",
    "Rubber stamp details Copy4",
    "Rubber stamp details Copy5",
    "Rubber stamp details Copy6",
    "Rubber stamp details Copy7",
    "Rubber stamp Text Alingnment",
    "Rubber stamp Area",
    "Rubber stamp COLOUR",
    "Ruber stamp MODEL CODE",
    "Rubber Stamp TYPE Copy",
    "Rubber Stamp case",
    "Rubber Stamp case Copy",
    "Rubber Stamp case Copy2",
    "Rubber Stamp case Copy3",
    "Rubber Stamp case Copy4",
    "Rubber Stamp case Copy5",
    "Rubber Stamp case Copy6",
    "Rubber Stamp case Copy7",
    "Rubber stamp Quantity",
    "Service type",
    "Quoted price",
    "Payment method",
    "payed ammount",
    "Invoice Number",
    "variance",
    "to pay",
    "amount due",
    "ART TOTAL QUOTED Copy",
    "variance 2",
    "variance 4",
    "variance 3",
    "variance 5",
    "variance 6",
    "variance 7",
    "variance 8",
    "variance 9",
    "Varience NOTES",
    "Varience details",
    "Varience details Copy",
    "Varience details Copy2",
    "Varience details Copy3",
    "Varience details Copy4",
    "Varience details Copy5",
    "Varience details Copy6",
    "Varience details Copy7",
    "Varience details Copy8",
    "Varience Item code QTY",
    "Varience Item code 1",
    "Varience Item code 2",
    "Varience Item code 3",
    "Varience Item code 4",
    "Varience Item code 5",
    "Varience Item code 6",
    "Varience Item code 7",
    "Varience Item code 8",
    "Varience Item code QTY 1",
    "Varience Item code QTY 2",
    "Varience Item code QTY 3",
    "Varience Item code QTY 4",
    "Varience Item code QTY 5",
    "Varience Item code QTY 6",
    "Varience Item code QTY 7",
    "Varience Item code QTY 8",
    "Invoice Number Copy",
    "payed ammount Copy",
    "Varience details Copy9",
    "Varience details Art 1",
    "Varience details Art 2",
    "Varience details Art 3",
    "Varience details Art 5",
    "Varience details Art 6",
    "Varience details Art 7",
    "Varience details Art 8",
    "Varience details Art 9",
    "Varience details Art 4",
    "Varience details Art 10",
    "Varience details Art 11",
    "Varience details Art 12",
    "Varience details Art 13",
    "Varience details Art 14",
    "Varience details Art 15",
    "Varience details Art Time",
    "Varience details Art Time 2",
    "Varience details Art Time 3",
    "Varience details Art Time 4",
    "Varience details Art Time 5",
    "Varience details Art Time 6",
    "Varience details Art Time 7",
    "Varience details Art Time 8",
    "Varience details Art Time 9",
    "Varience details Art Time 10",
    "Varience details Art Time 11",
    "Varience details Art Time 12",
    "Varience details Art Time 13",
    "Varience details Art Time 14",
    "Varience details Art Time 15",
    "Varience details Art cost",
    "Varience details Art cost 2",
    "Varience details Art cost 3",
    "Varience details Art cost 4",
    "Varience details Art cost 5",
    "Varience details Art cost 6",
    "Varience details Art cost 7",
    "Varience details Art cost 8",
    "Varience details Art cost 9",
    "Varience details Art cost 10",
    "Varience details Art cost 11",
    "Varience details Art cost 12",
    "Varience details Art cost 13",
    "Varience details Art cost 14",
    "Varience details Art cost 15",
    "amount of art time Hours",
    "amount due Art cost",
    "amount of art time Hours Div",
    "EYELETS",
    "Media TYPE",
    "amount due Art cost Copy",
    "Varience Item code 9",
    "Varience Item code 10",
    "Varience Item code QTY 9",
    "Varience Item code QTY 10",
    "variance 10",
    "variance 1",
    "Unit price 1",
    "Unit price 2",
    "Unit price 3",
    "Unit price 4",
    "Unit price 5",
    "Unit price 10",
    "Unit price 6",
    "Unit price 7",
    "Unit price 8",
    "Unit price 9",
    "HOW MANY VINYL",
    "PAPER SIZE VINYL",
    "COLOUR / BW VINYL",
    "CUT VINYL",
    "Lamination VINYL",
    "Sheet count VINYL",
    "WIDE MOUNTING VINYL",
    "WIDE MOUNTING VINYL stock",
    "EYELETS VINYL",
    "Display lABEL TYPE",
    "notified by time",
    "Vinyl Sides mounted",
    "HOW MANY COPYS vinyl art",
    "HOW MANY COPYS BAN artwork",
    "Customer Order Number",
    "Job Quote",
    "Commercial lables Notes",
    "Commercial lables Type",
    "HOW MANY COMMERCIAL LABELS",
    "Type of Cut commercial Lable",
    "application commercial label",
    "SHAPE commercial label",
    "PAPER SIZE LABEL commercial label",
    "COLOUR BW commercial label",
    "lABEL COMM ROLL commercial label",
    "SUB CONTRACTORS commercial label",
    "lABEL BOXES commercial label",
    "core size commercial label",
    "Presentation commercial label",
    "Lamination  commercial label",
    "lABEL COMM ROLL FEED",
    "lABEL TYPE Commercial",
    "Sheet count commercial",
    "DIE COMMERCIAL",
    "Media TYPE heatpress",
    "PAPER TYPE cut FABRIC",
    "fabric size",
]
