host: HOST
port: PORT

# Settings used by server.
fm_host: HOST
fm_port: PORT
fm_dsn: FILEMAKER_ODBC_DSN
fm_user: FILEMAKER_USER
fm_password: FILEMAKER_PASSWORD
fm_table: FILEMAKER_MODEL_TABLE

fm_max_connection_attempts: 10
fm_connection_attempt_delay: 30 # Seconds

fields:
  id: jobsheet number
  ref: Customer Order Number
  job_name: Job Name
  phone_number: Ph/Mob
  items:
    - code: Varience Item code 1
      description: Varience details
      quantity: Varience Item code QTY 1
      unit_price: Unit price 1
    - code: Varience Item code 2
      description: Varience details Copy
      quantity: Varience Item code QTY 2
      unit_price: Unit price 2
    - code: Varience Item code 3
      description: Varience details Copy2
      quantity: Varience Item code QTY 3
      unit_price: Unit price 3
    - code: Varience Item code 4
      description: Varience details Copy3
      quantity: Varience Item code QTY 4
      unit_price: Unit price 4
    - code: Varience Item code 5
      description: Varience details Copy4
      quantity: Varience Item code QTY 5
      unit_price: Unit price 5
    - code: Varience Item code 6
      description: Varience details Copy5
      quantity: Varience Item code QTY 6
      unit_price: Unit price 6
    - code: Varience Item code 7
      description: Varience details Copy6
      quantity: Varience Item code QTY 7
      unit_price: Unit price 7
    - code: Varience Item code 8
      description: Varience details Copy7
      quantity: Varience Item code QTY 8
      unit_price: Unit price 8
    - code: Varience Item code 9
      description: Varience details Copy8
      quantity: Varience Item code QTY 9
      unit_price: Unit price 9
    - code: Varience Item code 10
      description: Varience details Copy9
      quantity: Varience Item code QTY 10
      unit_price: Unit price 10
  art:
    - description: Varience details Art 1
      quantity: Varience details Art Time
      price: Varience details Art cost
    - description: Varience details Art 2
      quantity: Varience details Art Time 2
      price: Varience details Art cost 2
    - description: Varience details Art 3
      quantity: Varience details Art Time 3
      price: Varience details Art cost 3
    - description: Varience details Art 4
      quantity: Varience details Art Time 4
      price: Varience details Art cost 4
    - description: Varience details Art 5
      quantity: Varience details Art Time 5
      price: Varience details Art cost 5
    - description: Varience details Art 6
      quantity: Varience details Art Time 6
      price: Varience details Art cost 6
    - description: Varience details Art 7
      quantity: Varience details Art Time 7
      price: Varience details Art cost 7
    - description: Varience details Art 8
      quantity: Varience details Art Time 8
      price: Varience details Art cost 8
    - description: Varience details Art 9
      quantity: Varience details Art Time 9
      price: Varience details Art cost 9
    - description: Varience details Art 10
      quantity: Varience details Art Time 10
      price: Varience details Art cost 10
    - description: Varience details Art 11
      quantity: Varience details Art Time 11
      price: Varience details Art cost 11
    - description: Varience details Art 12
      quantity: Varience details Art Time 12
      price: Varience details Art cost 12
    - description: Varience details Art 13
      quantity: Varience details Art Time 13
      price: Varience details Art cost 13
    - description: Varience details Art 14
      quantity: Varience details Art Time 14
      price: Varience details Art cost 14
    - description: Varience details Art 15
      quantity: Varience details Art Time 15
      price: Varience details Art cost 15
  payments:
    - amount: payed ammount
      invoice: Invoice Number
    - amount: payed ammount Copy
      invoice: Invoice Number Copy
